package de.hawhh.gewiss.get.core.model;

/**
 * Enumeration of heating types.
 *
 * @author Nils Weiss
 */
public enum HeatingType {

    LOW_TEMPERATURE_BOILER, DISTRICT_HEAT, CONDENSING_BOILER, CONDENSING_BOILER_SOLAR, PELLETS, CONDENSING_BOILER_SOLAR_HEAT_RECOVERY, HEAT_PUMP_HEAT_RECOVERY, PELLETS_SOLAR_HEAT_RECOVERY, DISTRICT_HEAT_HEAT_RECOVERY
}
